Adding list of classes taken and list of current classes to student
Airbenders-490/profile pull request #15
Opened 2022-02-07 06:36 UTC by aminebechrifa

Instead of adding new methods to the repository , The update method was changed so that it can be used directly for both adding classes from the usecase layer

2022-02-07 07:58 UTC, nuzurie commented
Were you able to test it out? I don't think this will work.

2022-02-07 22:48 UTC, car12lin12 commented on Student/repository/student_create.sql
> +    classes_taken character varying(1024) COLLATE pg_catalog."default",
The duplicate of classes_taken should be enrolled_in

2022-02-10 19:30 UTC, car12lin12 requested changes
Nice job Amine! I have a similar question to Zubair, was this tested?

2022-02-10 19:30 UTC, car12lin12 commented on Student/repository/student_repository.go
> +	_, err = tx.Exec(ctx, update, st.ID, st.FirstName, st.LastName, st.Email, st.GeneralInfo,st.CurrentClasses,st.ClassesTaken, st.CreatedAt, st.UpdatedAt)
is it okay if the order here (current classes, classes taken) doesnt match line 28 (classes taken, current classes)?

2022-02-19 21:35 UTC, closed without merging