Feature/endorse teammates
Airbenders-490/profile pull request #4
Opened 2021-11-04 02:31 UTC by nuzurie

2021-11-07 20:28 UTC, aminebechrifa requested changes

2021-11-07 20:28 UTC, aminebechrifa commented on Review/delivery/http/review_delivery.go
> +	var student domain.Student
to be removed , not used later

2021-11-07 20:28 UTC, aminebechrifa commented on Review/delivery/http/review_delivery.go
> +	err = c.ShouldBindJSON(&student)
not used later

2021-11-07 20:28 UTC, aminebechrifa commented on Review/delivery/http/review_delivery.go
> +	if logged != reviewer {
return after this

2021-11-07 20:28 UTC, aminebechrifa commented on Review/delivery/http/review_delivery.go
> +	if loggedID != reviewer {
return after this

2021-11-08 00:50 UTC, nuzurie commented on Review/delivery/http/review_delivery.go
> +	reviewer, _ := loggedID.(string)
Bug: make sure the loggedID is the same as the reviewer's ID

2021-11-08 00:50 UTC, nuzurie commented on Review/delivery/http/review_delivery.go
> +	reviewer, _ := loggedID.(string)
set the reviewer's ID in the review

2021-11-08 00:53 UTC, nuzurie commented on Review/delivery/http/review_delivery.go
> +	if err != nil || review.Reviewed.ID == "" || review.Tags == nil {
Make this conditional inline

2021-11-08 02:24 UTC, car12lin12 approved these changes
Nice job

2021-11-08 02:25 UTC, merged

2021-11-08 02:25 UTC, stellakimnguyen approved these changes